In [15]:
import os
import pandas as pd
import re

### Atomic proportion

In [6]:
data_folder = "../data/proportional"

In [20]:
filter_contains = "ChiSquared"
data = []

def num_fast_slow(fn):
    with open(fn, "r") as in_xml:
        xml_str = in_xml.read()
        return xml_str.count("fast"), xml_str.count("slow")

for file in os.listdir(data_folder):
    if not filter_contains in file or not file.endswith(".xml"):
        continue
        
    match = re.search("s-([0-9]+).*_p([0-9]+)-([0-9]+)", file)
    if not match:
        continue
    
    num_fast, num_slow = num_fast_slow(os.path.join(data_folder, file))
    num_fast -= 2
    data.append(match.groups() + (num_fast, num_slow))

In [22]:
data = sorted(data, key=lambda x: int(x[1]))
df = pd.DataFrame(data, columns=["size", "pods_fast", "pods_slow", "atomics_fast", "atomics_slow"])

In [23]:
df

   size pods_fast pods_slow  atomics_fast  atomics_slow
0    15         1         1            98            99
1    15         2         1           131            66
2    15         3         1           147            50
3    15         4         1           157            40
4    15         5         1           164            33
5    15         6         1           168            29
6    15         7         1           172            25
7    15         8         1           175            22
8    15         9         1           177            20
9    15        10         1           179            18
10   15        11         1           180            17
11   15        12         1           181            16
12   15        13         1           182            15
13   15        14         1           183            14
14   15        15         1           184            13
15   15        16         1           185            12
16   15        17         1           186            11
17   15        18         1           186            11
18   15        19         1           187            10
19   15        20         1           187            10
20   15        25         1           189             8
21   15        30         1           190             7
22   15        35         1           191             6
23   15        40         1           192             5
24   15        45         1           192             5
25   15        50         1           193             4
26   15        75         1           194             3
27   15       100         1           195             2